[project]
name = "site-backend"
version = "0.1.0"
description = "Django API backend from Tortoise Community"
authors = [
    {name = "Ryuga",email = "vaishnav2353@gmail.com"}
]
license = {text = "MIT LICENSE"}
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django (>=6.0.5,<7.0.0)",
    "djangorestframework (>=3.17.1,<4.0.0)",
    "psycopg2-binary (>=2.9.12,<3.0.0)",
    "python-decouple (>=3.8,<4.0)",
    "django-cors-headers (>=4.9.0,<5.0.0)",
    "httpx (>=0.28.1,<0.29.0)",
    "gunicorn (>=26.0.0,<27.0.0)",
    "dj-database-url (>=3.1.2,<4.0.0)",
    "django-hosts (>=7.0.0,<8.0.0)",
    "djangorestframework-simplejwt (>=5.5.1,<6.0.0)",
    "cryptography (>=49.0.0,<50.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "flake8 (>=7.3.0,<8.0.0)"
]
