# Generated by Django 6.0.5 on 2026-06-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="discord_access_token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="discord_refresh_token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
