# Generated by Django 6.0.5 on 2026-07-15 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0003_alter_member_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="discord_access_token",
        ),
        migrations.RemoveField(
            model_name="user",
            name="discord_access_token_expiry",
        ),
        migrations.RemoveField(
            model_name="user",
            name="discord_refresh_token",
        ),
        migrations.CreateModel(
            name="OauthToken",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("access", "Access Token"),
                            ("refresh", "Refresh Token"),
                        ],
                        default="access",
                        max_length=7,
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("discord", "Discord Token"),
                            ("github", "Github Token"),
                            ("google", "Google Token"),
                        ],
                        default="discord",
                        max_length=7,
                    ),
                ),
                ("value", models.CharField(blank=True, max_length=100, null=True)),
                ("expiry", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oauth_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
