# Generated by Django 6.0.5 on 2026-07-15 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0004_remove_user_discord_access_token_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="banned",
        ),
        migrations.CreateModel(
            name="BannedMember",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expires", models.DateTimeField(blank=True, null=True)),
                (
                    "member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="common.member"
                    ),
                ),
            ],
        ),
    ]
